// Flat config (ESLint 9). Deliberately close to the recommended presets: this
// package is ~1k lines of library code, and a bespoke rule set would be a
// second opinion to maintain for no benefit. The floor is "lint runs and can
// fail", not "lint encodes taste".
import js from '@eslint/js';
import globals from 'globals';
import reactHooks from 'eslint-plugin-react-hooks';
import tseslint from 'typescript-eslint';

export default tseslint.config(
  {
    // dist/ is generated by `tsc`; examples/ is a standalone Next.js app with
    // its own toolchain and is not part of this package's published `files`.
    //
    // .claude/ holds per-session git worktrees — each a full copy of this repo,
    // generated dist/ included. These patterns are anchored at the project root,
    // so `dist/**` does NOT match `.claude/worktrees/x/dist/**`: without this
    // entry a worktree is linted as source and reports errors in files that are
    // not part of the checkout being tested.
    ignores: ['dist/**', 'examples/**', 'node_modules/**', '.claude/**'],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  {
    files: ['**/*.ts'],
    languageOptions: { globals: globals.node },
    rules: {
      // The public API intentionally accepts arbitrary user-supplied form
      // shapes, so a handful of `any`s are load-bearing rather than lazy.
      // Warn, so they stay visible without failing the gate on existing code.
      '@typescript-eslint/no-explicit-any': 'warn',
    },
  },
  {
    // src/react.ts exports a hook, and already carries an
    // `eslint-disable-next-line react-hooks/exhaustive-deps`. Without the
    // plugin installed that directive is itself an ESLint error ("rule not
    // found") — the comment was writing a cheque the config could not cash.
    // Installing it makes the suppression meaningful AND lints the hook.
    files: ['src/react.ts'],
    plugins: { 'react-hooks': reactHooks },
    rules: reactHooks.configs.recommended.rules,
  },
  {
    // Tests and scripts are plain Node under `node --test`. `Request`/`URL`
    // are Node 18+ globals, so they need the node globals set to resolve.
    files: ['test/**/*.js', 'scripts/**/*.{js,mjs}'],
    languageOptions: { globals: { ...globals.node, ...globals.nodeBuiltin } },
  },
);
